// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/top5week.ts";
import * as $$$$0 from "./routes/styles.css.ts";
import * as $$$$1 from "./routes/_app.tsx";
import * as $$$$$0 from "./islands/FlyingBacons.tsx";
import * as $$$$$$$$0 from "./sections/Container.tsx";
import * as $$$$$$$$1 from "./sections/Footer.tsx";
import * as $$$$$$$$2 from "./sections/Hero.tsx";
import * as $$$$$$$$3 from "./sections/HQSelectorList.tsx";
import * as $$$$$$$$4 from "./sections/ParagraphList.tsx";
import * as $$$$$$$$5 from "./sections/SimpleTextList.tsx";
import * as $$$$$$$$6 from "./sections/Theme.tsx";
import * as $$$$$$$$7 from "./sections/Top5AndCat.tsx";
import * as $live_workflows from "deco/routes/live/workflows/run.ts";
import * as $live_middleware from "deco/routes/_middleware.ts";
import * as $live_workbench from "deco/routes/live/workbench.ts";
import * as $live_invoke from "deco/routes/live/invoke/index.ts";
import * as $live_invoke_key from "deco/routes/live/invoke/[...key].ts";
import * as $live_editorData from "deco/routes/live/editorData.ts";
import * as $live_inspect from "deco/routes/live/inspect/[...block].ts";
import * as $live_release from "deco/routes/live/release.ts";
import * as $live_meta from "deco/routes/live/_meta.ts";
import * as $live_previews_block from "deco/routes/live/previews/[...block].tsx";
import * as $live_previews_index from "deco/routes/live/previews/index.tsx";
import * as $live_catchall from "deco/routes/[...catchall].tsx";
import * as i1$0 from "deco/loaders/secret.ts";
import * as i1$1 from "deco/loaders/state.ts";
import * as i1$2 from "deco/loaders/workflows/events.ts";
import * as i1$3 from "deco/loaders/workflows/get.ts";
import * as i1$$0 from "deco/handlers/devPage.ts";
import * as i1$$1 from "deco/handlers/fresh.ts";
import * as i1$$2 from "deco/handlers/proxy.ts";
import * as i1$$3 from "deco/handlers/redirect.ts";
import * as i1$$4 from "deco/handlers/router.ts";
import * as i1$$5 from "deco/handlers/routesSelection.ts";
import * as i1$$6 from "deco/handlers/workflowRunner.ts";
import * as i1$$$0 from "deco/pages/LivePage.tsx";
import * as i1$$$$0 from "deco/sections/Conditional_Beta.tsx";
import * as i1$$$$1 from "deco/sections/EmptySection.tsx";
import * as i1$$$$2 from "deco/sections/PageInclude.tsx";
import * as i1$$$$3 from "deco/sections/Slot.tsx";
import * as i1$$$$4 from "deco/sections/UseSlot.tsx";
import * as i1$$$$$0 from "deco/matchers/MatchAlways.ts";
import * as i1$$$$$1 from "deco/matchers/MatchCron.ts";
import * as i1$$$$$2 from "deco/matchers/MatchDate.ts";
import * as i1$$$$$3 from "deco/matchers/MatchDevice.ts";
import * as i1$$$$$4 from "deco/matchers/MatchEnvironment.ts";
import * as i1$$$$$5 from "deco/matchers/MatchHost.ts";
import * as i1$$$$$6 from "deco/matchers/MatchLocation.ts";
import * as i1$$$$$7 from "deco/matchers/MatchMulti.ts";
import * as i1$$$$$8 from "deco/matchers/MatchRandom.ts";
import * as i1$$$$$9 from "deco/matchers/MatchSite.ts";
import * as i1$$$$$10 from "deco/matchers/MatchUserAgent.ts";
import * as i1$$$$$$0 from "deco/flags/audience.ts";
import * as i1$$$$$$1 from "deco/flags/everyone.ts";
import * as i1$$$$$$2 from "deco/flags/flag.ts";
import * as i1$$$$$$3 from "deco/flags/multivariate.ts";
import * as i1$$$$$$$0 from "deco/actions/secrets/encrypt.ts";
import * as i1$$$$$$$1 from "deco/actions/workflows/cancel.ts";
import * as i1$$$$$$$2 from "deco/actions/workflows/signal.ts";
import * as i1$$$$$$$3 from "deco/actions/workflows/start.ts";
import * as i2$0 from "deco-sites/std/functions/butterCMSAds.ts";
import * as i2$1 from "deco-sites/std/functions/butterCMSBrands.ts";
import * as i2$2 from "deco-sites/std/functions/butterCMSCategories.ts";
import * as i2$3 from "deco-sites/std/functions/butterCMSFeaturedPosts.ts";
import * as i2$4 from "deco-sites/std/functions/butterCMSPage.ts";
import * as i2$5 from "deco-sites/std/functions/butterCMSPlaces.ts";
import * as i2$6 from "deco-sites/std/functions/butterCMSPostDetail.ts";
import * as i2$7 from "deco-sites/std/functions/butterCMSPosts.ts";
import * as i2$8 from "deco-sites/std/functions/butterCMSRelatedPosts.ts";
import * as i2$9 from "deco-sites/std/functions/occProductDetailsPage.ts";
import * as i2$10 from "deco-sites/std/functions/requestToParam.ts";
import * as i2$11 from "deco-sites/std/functions/shopifyProductDetailsPage.ts";
import * as i2$12 from "deco-sites/std/functions/shopifyProductList.ts";
import * as i2$13 from "deco-sites/std/functions/shopifyProductListingPage.ts";
import * as i2$14 from "deco-sites/std/functions/vndaProductList.ts";
import * as i2$15 from "deco-sites/std/functions/vndaProductListingPage.ts";
import * as i2$16 from "deco-sites/std/functions/vtexLegacyProductDetailsPage.ts";
import * as i2$17 from "deco-sites/std/functions/vtexLegacyProductList.ts";
import * as i2$18 from "deco-sites/std/functions/vtexLegacyProductListingPage.ts";
import * as i2$19 from "deco-sites/std/functions/vtexLegacyRelatedProductsLoader.ts";
import * as i2$20 from "deco-sites/std/functions/vtexNavbar.ts";
import * as i2$21 from "deco-sites/std/functions/vtexProductDetailsPage.ts";
import * as i2$22 from "deco-sites/std/functions/vtexProductList.ts";
import * as i2$23 from "deco-sites/std/functions/vtexProductListingPage.ts";
import * as i2$24 from "deco-sites/std/functions/vtexSuggestions.ts";
import * as i2$25 from "deco-sites/std/functions/vtexWishlist.ts";
import * as i2$$0 from "deco-sites/std/accounts/butterCMS.ts";
import * as i2$$1 from "deco-sites/std/accounts/linxImpulse.ts";
import * as i2$$2 from "deco-sites/std/accounts/nuvemShop.ts";
import * as i2$$3 from "deco-sites/std/accounts/occ.ts";
import * as i2$$4 from "deco-sites/std/accounts/shopify.ts";
import * as i2$$5 from "deco-sites/std/accounts/vnda.ts";
import * as i2$$6 from "deco-sites/std/accounts/vtex.ts";
import * as i2$$7 from "deco-sites/std/accounts/yourViews.ts";
import * as i2$$$0 from "deco-sites/std/loaders/linxImpulse/autocompletes/popular.ts";
import * as i2$$$1 from "deco-sites/std/loaders/linxImpulse/autocompletes/suggestions.ts";
import * as i2$$$2 from "deco-sites/std/loaders/linxImpulse/pages/recommendations.ts";
import * as i2$$$3 from "deco-sites/std/loaders/linxImpulse/products/similarItems.ts";
import * as i2$$$4 from "deco-sites/std/loaders/linxImpulse/search.ts";
import * as i2$$$5 from "deco-sites/std/loaders/nuvemShop/nuvemShopProductDetailsPage.ts";
import * as i2$$$6 from "deco-sites/std/loaders/nuvemShop/nuvemShopProductList.ts";
import * as i2$$$7 from "deco-sites/std/loaders/nuvemShop/nuvemShopProductListingPage.ts";
import * as i2$$$8 from "deco-sites/std/loaders/vnda/cart.ts";
import * as i2$$$9 from "deco-sites/std/loaders/vnda/productDetailsPage.ts";
import * as i2$$$10 from "deco-sites/std/loaders/vnda/productList.ts";
import * as i2$$$11 from "deco-sites/std/loaders/vnda/productListingPage.ts";
import * as i2$$$12 from "deco-sites/std/loaders/vnda/proxy.ts";
import * as i2$$$13 from "deco-sites/std/loaders/vtex/cart.ts";
import * as i2$$$14 from "deco-sites/std/loaders/vtex/intelligentSearch/productDetailsPage.ts";
import * as i2$$$15 from "deco-sites/std/loaders/vtex/intelligentSearch/productList.ts";
import * as i2$$$16 from "deco-sites/std/loaders/vtex/intelligentSearch/productListingPage.ts";
import * as i2$$$17 from "deco-sites/std/loaders/vtex/intelligentSearch/suggestions.ts";
import * as i2$$$18 from "deco-sites/std/loaders/vtex/legacy/productDetailsPage.ts";
import * as i2$$$19 from "deco-sites/std/loaders/vtex/legacy/productList.ts";
import * as i2$$$20 from "deco-sites/std/loaders/vtex/legacy/productListingPage.ts";
import * as i2$$$21 from "deco-sites/std/loaders/vtex/legacy/relatedProductsLoader.ts";
import * as i2$$$22 from "deco-sites/std/loaders/vtex/legacy/suggestions.ts";
import * as i2$$$23 from "deco-sites/std/loaders/vtex/navbar.ts";
import * as i2$$$24 from "deco-sites/std/loaders/vtex/proxy.ts";
import * as i2$$$25 from "deco-sites/std/loaders/vtex/user.ts";
import * as i2$$$26 from "deco-sites/std/loaders/vtex/wishlist.ts";
import * as i2$$$27 from "deco-sites/std/loaders/x/font.ts";
import * as i2$$$28 from "deco-sites/std/loaders/x/image.ts";
import * as i2$$$29 from "deco-sites/std/loaders/x/redirects.ts";
import * as i2$$$30 from "deco-sites/std/loaders/x/redirectsFromCsv.ts";
import * as i2$$$$0 from "deco-sites/std/handlers/sitemap.ts";
import * as i2$$$$1 from "deco-sites/std/handlers/vtex/sitemap.ts";
import * as i2$$$$$0 from "deco-sites/std/sections/Analytics.tsx";
import * as i2$$$$$1 from "deco-sites/std/sections/configButterCMS.global.tsx";
import * as i2$$$$$2 from "deco-sites/std/sections/configLinxImpulse.global.tsx";
import * as i2$$$$$3 from "deco-sites/std/sections/configNuvemShop.tsx";
import * as i2$$$$$4 from "deco-sites/std/sections/configOCC.global.tsx";
import * as i2$$$$$5 from "deco-sites/std/sections/configShopify.global.tsx";
import * as i2$$$$$6 from "deco-sites/std/sections/configVTEX.global.tsx";
import * as i2$$$$$7 from "deco-sites/std/sections/configYourViews.global.tsx";
import * as i2$$$$$8 from "deco-sites/std/sections/SEO.tsx";
import * as i2$$$$$9 from "deco-sites/std/sections/SEOPDP.tsx";
import * as i2$$$$$10 from "deco-sites/std/sections/SEOPLP.tsx";
import * as i2$$$$$11 from "deco-sites/std/sections/VTEXPortalDataLayerCompatibility.tsx";
import * as i2$$$$$$0 from "deco-sites/std/actions/vnda/cart/addItem.ts";
import * as i2$$$$$$1 from "deco-sites/std/actions/vnda/cart/setShippingAddress.ts";
import * as i2$$$$$$2 from "deco-sites/std/actions/vnda/cart/updateCoupon.ts";
import * as i2$$$$$$3 from "deco-sites/std/actions/vnda/cart/updateItem.ts";
import * as i2$$$$$$4 from "deco-sites/std/actions/vtex/analytics/sendEvent.ts";
import * as i2$$$$$$5 from "deco-sites/std/actions/vtex/cart/addItems.ts";
import * as i2$$$$$$6 from "deco-sites/std/actions/vtex/cart/getInstallment.ts";
import * as i2$$$$$$7 from "deco-sites/std/actions/vtex/cart/removeItemAttachment.ts";
import * as i2$$$$$$8 from "deco-sites/std/actions/vtex/cart/removeItems.ts";
import * as i2$$$$$$9 from "deco-sites/std/actions/vtex/cart/simulation.ts";
import * as i2$$$$$$10 from "deco-sites/std/actions/vtex/cart/updateAttachment.ts";
import * as i2$$$$$$11 from "deco-sites/std/actions/vtex/cart/updateCoupons.ts";
import * as i2$$$$$$12 from "deco-sites/std/actions/vtex/cart/updateItemAttachment.ts";
import * as i2$$$$$$13 from "deco-sites/std/actions/vtex/cart/updateItemPrice.ts";
import * as i2$$$$$$14 from "deco-sites/std/actions/vtex/cart/updateItems.ts";
import * as i2$$$$$$15 from "deco-sites/std/actions/vtex/cart/updateProfile.ts";
import * as i2$$$$$$16 from "deco-sites/std/actions/vtex/cart/updateUser.ts";
import * as i2$$$$$$17 from "deco-sites/std/actions/vtex/newsletter/subscribe.ts";
import * as i2$$$$$$18 from "deco-sites/std/actions/vtex/notifyme.ts";
import * as i2$$$$$$19 from "deco-sites/std/actions/vtex/wishlist/addItem.ts";
import * as i2$$$$$$20 from "deco-sites/std/actions/vtex/wishlist/removeItem.ts";

const manifest = {
  "loaders": {
    "$live/loaders/secret.ts": i1$0,
    "$live/loaders/state.ts": i1$1,
    "$live/loaders/workflows/events.ts": i1$2,
    "$live/loaders/workflows/get.ts": i1$3,
    "deco-sites/std/loaders/linxImpulse/autocompletes/popular.ts": i2$$$0,
    "deco-sites/std/loaders/linxImpulse/autocompletes/suggestions.ts": i2$$$1,
    "deco-sites/std/loaders/linxImpulse/pages/recommendations.ts": i2$$$2,
    "deco-sites/std/loaders/linxImpulse/products/similarItems.ts": i2$$$3,
    "deco-sites/std/loaders/linxImpulse/search.ts": i2$$$4,
    "deco-sites/std/loaders/nuvemShop/nuvemShopProductDetailsPage.ts": i2$$$5,
    "deco-sites/std/loaders/nuvemShop/nuvemShopProductList.ts": i2$$$6,
    "deco-sites/std/loaders/nuvemShop/nuvemShopProductListingPage.ts": i2$$$7,
    "deco-sites/std/loaders/vnda/cart.ts": i2$$$8,
    "deco-sites/std/loaders/vnda/productDetailsPage.ts": i2$$$9,
    "deco-sites/std/loaders/vnda/productList.ts": i2$$$10,
    "deco-sites/std/loaders/vnda/productListingPage.ts": i2$$$11,
    "deco-sites/std/loaders/vnda/proxy.ts": i2$$$12,
    "deco-sites/std/loaders/vtex/cart.ts": i2$$$13,
    "deco-sites/std/loaders/vtex/intelligentSearch/productDetailsPage.ts":
      i2$$$14,
    "deco-sites/std/loaders/vtex/intelligentSearch/productList.ts": i2$$$15,
    "deco-sites/std/loaders/vtex/intelligentSearch/productListingPage.ts":
      i2$$$16,
    "deco-sites/std/loaders/vtex/intelligentSearch/suggestions.ts": i2$$$17,
    "deco-sites/std/loaders/vtex/legacy/productDetailsPage.ts": i2$$$18,
    "deco-sites/std/loaders/vtex/legacy/productList.ts": i2$$$19,
    "deco-sites/std/loaders/vtex/legacy/productListingPage.ts": i2$$$20,
    "deco-sites/std/loaders/vtex/legacy/relatedProductsLoader.ts": i2$$$21,
    "deco-sites/std/loaders/vtex/legacy/suggestions.ts": i2$$$22,
    "deco-sites/std/loaders/vtex/navbar.ts": i2$$$23,
    "deco-sites/std/loaders/vtex/proxy.ts": i2$$$24,
    "deco-sites/std/loaders/vtex/user.ts": i2$$$25,
    "deco-sites/std/loaders/vtex/wishlist.ts": i2$$$26,
    "deco-sites/std/loaders/x/font.ts": i2$$$27,
    "deco-sites/std/loaders/x/image.ts": i2$$$28,
    "deco-sites/std/loaders/x/redirects.ts": i2$$$29,
    "deco-sites/std/loaders/x/redirectsFromCsv.ts": i2$$$30,
    "deco-sites/ultimato/loaders/top5week.ts": $$$0,
  },
  "routes": {
    "./routes/_app.tsx": $$$$1,
    "./routes/_middleware.ts": $live_middleware,
    "./routes/[...catchall].tsx": $live_catchall,
    "./routes/index.tsx": $live_catchall,
    "./routes/live/_meta.ts": $live_meta,
    "./routes/live/editorData.ts": $live_editorData,
    "./routes/live/inspect/[...block].ts": $live_inspect,
    "./routes/live/invoke/[...key].ts": $live_invoke_key,
    "./routes/live/invoke/index.ts": $live_invoke,
    "./routes/live/previews/[...block].tsx": $live_previews_block,
    "./routes/live/previews/index.tsx": $live_previews_index,
    "./routes/live/release.ts": $live_release,
    "./routes/live/workbench.ts": $live_workbench,
    "./routes/live/workflows/run.ts": $live_workflows,
    "./routes/styles.css.ts": $$$$0,
  },
  "islands": {
    "./islands/FlyingBacons.tsx": $$$$$0,
  },
  "sections": {
    "$live/sections/Conditional_Beta.tsx": i1$$$$0,
    "$live/sections/EmptySection.tsx": i1$$$$1,
    "$live/sections/PageInclude.tsx": i1$$$$2,
    "$live/sections/Slot.tsx": i1$$$$3,
    "$live/sections/UseSlot.tsx": i1$$$$4,
    "deco-sites/std/sections/Analytics.tsx": i2$$$$$0,
    "deco-sites/std/sections/configButterCMS.global.tsx": i2$$$$$1,
    "deco-sites/std/sections/configLinxImpulse.global.tsx": i2$$$$$2,
    "deco-sites/std/sections/configNuvemShop.tsx": i2$$$$$3,
    "deco-sites/std/sections/configOCC.global.tsx": i2$$$$$4,
    "deco-sites/std/sections/configShopify.global.tsx": i2$$$$$5,
    "deco-sites/std/sections/configVTEX.global.tsx": i2$$$$$6,
    "deco-sites/std/sections/configYourViews.global.tsx": i2$$$$$7,
    "deco-sites/std/sections/SEO.tsx": i2$$$$$8,
    "deco-sites/std/sections/SEOPDP.tsx": i2$$$$$9,
    "deco-sites/std/sections/SEOPLP.tsx": i2$$$$$10,
    "deco-sites/std/sections/VTEXPortalDataLayerCompatibility.tsx": i2$$$$$11,
    "deco-sites/ultimato/sections/Container.tsx": $$$$$$$$0,
    "deco-sites/ultimato/sections/Footer.tsx": $$$$$$$$1,
    "deco-sites/ultimato/sections/Hero.tsx": $$$$$$$$2,
    "deco-sites/ultimato/sections/HQSelectorList.tsx": $$$$$$$$3,
    "deco-sites/ultimato/sections/ParagraphList.tsx": $$$$$$$$4,
    "deco-sites/ultimato/sections/SimpleTextList.tsx": $$$$$$$$5,
    "deco-sites/ultimato/sections/Theme.tsx": $$$$$$$$6,
    "deco-sites/ultimato/sections/Top5AndCat.tsx": $$$$$$$$7,
  },
  "name": "deco-sites/ultimato",
  "handlers": {
    "$live/handlers/devPage.ts": i1$$0,
    "$live/handlers/fresh.ts": i1$$1,
    "$live/handlers/proxy.ts": i1$$2,
    "$live/handlers/redirect.ts": i1$$3,
    "$live/handlers/router.ts": i1$$4,
    "$live/handlers/routesSelection.ts": i1$$5,
    "$live/handlers/workflowRunner.ts": i1$$6,
    "deco-sites/std/handlers/sitemap.ts": i2$$$$0,
    "deco-sites/std/handlers/vtex/sitemap.ts": i2$$$$1,
  },
  "pages": {
    "$live/pages/LivePage.tsx": i1$$$0,
  },
  "matchers": {
    "$live/matchers/MatchAlways.ts": i1$$$$$0,
    "$live/matchers/MatchCron.ts": i1$$$$$1,
    "$live/matchers/MatchDate.ts": i1$$$$$2,
    "$live/matchers/MatchDevice.ts": i1$$$$$3,
    "$live/matchers/MatchEnvironment.ts": i1$$$$$4,
    "$live/matchers/MatchHost.ts": i1$$$$$5,
    "$live/matchers/MatchLocation.ts": i1$$$$$6,
    "$live/matchers/MatchMulti.ts": i1$$$$$7,
    "$live/matchers/MatchRandom.ts": i1$$$$$8,
    "$live/matchers/MatchSite.ts": i1$$$$$9,
    "$live/matchers/MatchUserAgent.ts": i1$$$$$10,
  },
  "flags": {
    "$live/flags/audience.ts": i1$$$$$$0,
    "$live/flags/everyone.ts": i1$$$$$$1,
    "$live/flags/flag.ts": i1$$$$$$2,
    "$live/flags/multivariate.ts": i1$$$$$$3,
  },
  "actions": {
    "$live/actions/secrets/encrypt.ts": i1$$$$$$$0,
    "$live/actions/workflows/cancel.ts": i1$$$$$$$1,
    "$live/actions/workflows/signal.ts": i1$$$$$$$2,
    "$live/actions/workflows/start.ts": i1$$$$$$$3,
    "deco-sites/std/actions/vnda/cart/addItem.ts": i2$$$$$$0,
    "deco-sites/std/actions/vnda/cart/setShippingAddress.ts": i2$$$$$$1,
    "deco-sites/std/actions/vnda/cart/updateCoupon.ts": i2$$$$$$2,
    "deco-sites/std/actions/vnda/cart/updateItem.ts": i2$$$$$$3,
    "deco-sites/std/actions/vtex/analytics/sendEvent.ts": i2$$$$$$4,
    "deco-sites/std/actions/vtex/cart/addItems.ts": i2$$$$$$5,
    "deco-sites/std/actions/vtex/cart/getInstallment.ts": i2$$$$$$6,
    "deco-sites/std/actions/vtex/cart/removeItemAttachment.ts": i2$$$$$$7,
    "deco-sites/std/actions/vtex/cart/removeItems.ts": i2$$$$$$8,
    "deco-sites/std/actions/vtex/cart/simulation.ts": i2$$$$$$9,
    "deco-sites/std/actions/vtex/cart/updateAttachment.ts": i2$$$$$$10,
    "deco-sites/std/actions/vtex/cart/updateCoupons.ts": i2$$$$$$11,
    "deco-sites/std/actions/vtex/cart/updateItemAttachment.ts": i2$$$$$$12,
    "deco-sites/std/actions/vtex/cart/updateItemPrice.ts": i2$$$$$$13,
    "deco-sites/std/actions/vtex/cart/updateItems.ts": i2$$$$$$14,
    "deco-sites/std/actions/vtex/cart/updateProfile.ts": i2$$$$$$15,
    "deco-sites/std/actions/vtex/cart/updateUser.ts": i2$$$$$$16,
    "deco-sites/std/actions/vtex/newsletter/subscribe.ts": i2$$$$$$17,
    "deco-sites/std/actions/vtex/notifyme.ts": i2$$$$$$18,
    "deco-sites/std/actions/vtex/wishlist/addItem.ts": i2$$$$$$19,
    "deco-sites/std/actions/vtex/wishlist/removeItem.ts": i2$$$$$$20,
  },
  "functions": {
    "deco-sites/std/functions/butterCMSAds.ts": i2$0,
    "deco-sites/std/functions/butterCMSBrands.ts": i2$1,
    "deco-sites/std/functions/butterCMSCategories.ts": i2$2,
    "deco-sites/std/functions/butterCMSFeaturedPosts.ts": i2$3,
    "deco-sites/std/functions/butterCMSPage.ts": i2$4,
    "deco-sites/std/functions/butterCMSPlaces.ts": i2$5,
    "deco-sites/std/functions/butterCMSPostDetail.ts": i2$6,
    "deco-sites/std/functions/butterCMSPosts.ts": i2$7,
    "deco-sites/std/functions/butterCMSRelatedPosts.ts": i2$8,
    "deco-sites/std/functions/occProductDetailsPage.ts": i2$9,
    "deco-sites/std/functions/requestToParam.ts": i2$10,
    "deco-sites/std/functions/shopifyProductDetailsPage.ts": i2$11,
    "deco-sites/std/functions/shopifyProductList.ts": i2$12,
    "deco-sites/std/functions/shopifyProductListingPage.ts": i2$13,
    "deco-sites/std/functions/vndaProductList.ts": i2$14,
    "deco-sites/std/functions/vndaProductListingPage.ts": i2$15,
    "deco-sites/std/functions/vtexLegacyProductDetailsPage.ts": i2$16,
    "deco-sites/std/functions/vtexLegacyProductList.ts": i2$17,
    "deco-sites/std/functions/vtexLegacyProductListingPage.ts": i2$18,
    "deco-sites/std/functions/vtexLegacyRelatedProductsLoader.ts": i2$19,
    "deco-sites/std/functions/vtexNavbar.ts": i2$20,
    "deco-sites/std/functions/vtexProductDetailsPage.ts": i2$21,
    "deco-sites/std/functions/vtexProductList.ts": i2$22,
    "deco-sites/std/functions/vtexProductListingPage.ts": i2$23,
    "deco-sites/std/functions/vtexSuggestions.ts": i2$24,
    "deco-sites/std/functions/vtexWishlist.ts": i2$25,
  },
  "accounts": {
    "deco-sites/std/accounts/butterCMS.ts": i2$$0,
    "deco-sites/std/accounts/linxImpulse.ts": i2$$1,
    "deco-sites/std/accounts/nuvemShop.ts": i2$$2,
    "deco-sites/std/accounts/occ.ts": i2$$3,
    "deco-sites/std/accounts/shopify.ts": i2$$4,
    "deco-sites/std/accounts/vnda.ts": i2$$5,
    "deco-sites/std/accounts/vtex.ts": i2$$6,
    "deco-sites/std/accounts/yourViews.ts": i2$$7,
  },
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
