// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/categories.ts";
import * as $$$1 from "./loaders/footer.ts";
import * as $$$2 from "./loaders/guias.ts";
import * as $$$3 from "./loaders/header.ts";
import * as $$$4 from "./loaders/news-carousel.ts";
import * as $$$5 from "./loaders/post-archive.ts";
import * as $$$6 from "./loaders/top5week.ts";
import * as $$$$$$0 from "./sections/Content/Categories.tsx";
import * as $$$$$$1 from "./sections/Content/Guias.tsx";
import * as $$$$$$2 from "./sections/Content/PostArchive.tsx";
import * as $$$$$$3 from "./sections/Content/Top5AndCat.tsx";
import * as $$$$$$4 from "./sections/Image/Highlight.tsx";
import * as $$$$$$5 from "./sections/Image/HQSelectorList.tsx";
import * as $$$$$$6 from "./sections/Image/Pigs.tsx";
import * as $$$$$$7 from "./sections/Image/PostsSlider.tsx";
import * as $$$$$$8 from "./sections/Layout/Container.tsx";
import * as $$$$$$9 from "./sections/Layout/Footer.tsx";
import * as $$$$$$10 from "./sections/Layout/Header.tsx";
import * as $$$$$$11 from "./sections/Layout/Hero.tsx";
import * as $$$$$$12 from "./sections/Other/WhatsappCTA.tsx";
import * as $$$$$$13 from "./sections/Theme.tsx";
import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";

const manifest = {
  "loaders": {
    "deco-sites/ultimato/loaders/categories.ts": $$$0,
    "deco-sites/ultimato/loaders/footer.ts": $$$1,
    "deco-sites/ultimato/loaders/guias.ts": $$$2,
    "deco-sites/ultimato/loaders/header.ts": $$$3,
    "deco-sites/ultimato/loaders/news-carousel.ts": $$$4,
    "deco-sites/ultimato/loaders/post-archive.ts": $$$5,
    "deco-sites/ultimato/loaders/top5week.ts": $$$6,
  },
  "sections": {
    "deco-sites/ultimato/sections/Content/Categories.tsx": $$$$$$0,
    "deco-sites/ultimato/sections/Content/Guias.tsx": $$$$$$1,
    "deco-sites/ultimato/sections/Content/PostArchive.tsx": $$$$$$2,
    "deco-sites/ultimato/sections/Content/Top5AndCat.tsx": $$$$$$3,
    "deco-sites/ultimato/sections/Image/Highlight.tsx": $$$$$$4,
    "deco-sites/ultimato/sections/Image/HQSelectorList.tsx": $$$$$$5,
    "deco-sites/ultimato/sections/Image/Pigs.tsx": $$$$$$6,
    "deco-sites/ultimato/sections/Image/PostsSlider.tsx": $$$$$$7,
    "deco-sites/ultimato/sections/Layout/Container.tsx": $$$$$$8,
    "deco-sites/ultimato/sections/Layout/Footer.tsx": $$$$$$9,
    "deco-sites/ultimato/sections/Layout/Header.tsx": $$$$$$10,
    "deco-sites/ultimato/sections/Layout/Hero.tsx": $$$$$$11,
    "deco-sites/ultimato/sections/Other/WhatsappCTA.tsx": $$$$$$12,
    "deco-sites/ultimato/sections/Theme.tsx": $$$$$$13,
  },
  "apps": {
    "deco-sites/ultimato/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/ultimato/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/ultimato",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
